name: "Pilar Quiroz"
description: "Pilar Quiroz is a Colombian actress, trained in Paris, working and living in Germany."

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount

permalink: pretty

highlighter: "none"